[package]
name = "chip-u8"
version = "0.1.0"
authors = ["Jesús Espino <jespinog@gmail.com>"]

[dependencies]
rand = "0.3"
sdl2 = "0.16"
docopt = "0.6.78"

[[bin]]
name = "decode-u8"
path = "src/decoderom.rs"

[[bin]]
name = "chip-u8"
path = "src/main.rs"
